Sikana improvements
endlessm/kolibri-channel-custom-web-app pull request #31
Opened 2021-03-23 17:10 UTC by manuq

https://phabricator.endlessm.com/T31419

2021-03-23 18:16 UTC, danigm approved these changes
Looks good to me.

The only thing that I don't like too much about this override is the need to copy the Card component, to just update the template.

I was thinking if it's possible to use some kind of [composition](https://v3.vuejs.org/api/options-composition.html) or something like that to simplify the code duplication, but I don't know if that could be something possible with the current dynamic components.

But maybe that's not part of this PR, so I think this is okay to be merged.

2021-03-23 18:20 UTC, danigm requested changes

2021-03-23 18:20 UTC, danigm commented on template-ui/channel-overrides/sikana/components/Card.vue
> +    }
Missing trailing comma

```suggestion
    },
```

2021-03-23 23:39 UTC, manuq commented
> Looks good to me.
> 
> The only thing that I don't like too much about this override is the need to copy the Card component, to just update the template.
> 
> I was thinking if it's possible to use some kind of [composition](https://v3.vuejs.org/api/options-composition.html) or something like that to simplify the code duplication, but I don't know if that could be something possible with the current dynamic components.
> 
> But maybe that's not part of this PR, so I think this is okay to be merged.

I would like to discuss this with you, probably you have a better idea for doing the overrides. By the way this is not only changing the <template> part, the <script> is also changed to import a new getLevel getter from Vuex.

Regarding the comma suggestion, I wonder if the linter is not detecting the overrides. Thanks for the fix.

2021-03-24 11:31 UTC, danigm approved these changes

2021-03-24 11:31 UTC, merged