template: Custom CarouselCard style
endlessm/kolibri-channel-custom-web-app pull request #43
Opened 2021-04-08 11:48 UTC by danigm

This patch modifies the CarouselCard template to show the thumbnail to
the left and the description to the right.

This can't be done with a simple <b-card img-left> because that will
draw the image with it's size and not every thumbnails has the same
size, so to be able to adapt the thumbnail to the half of the card we
need to use the cover css property and the thumbnail as background.

https://phabricator.endlessm.com/T31719

2021-04-08 13:36 UTC, manuq requested changes
Looks great, only needs to use the theme properly, and style in CSS as much as possible.

2021-04-08 13:36 UTC, manuq commented on template-ui/src/components/Carousel.vue
> +      borderRadius: 20,
There is `$border-radius-lg` in bootstrap, see in your `node_modules/bootstrap/scss/_variables.scss`. What I usually do to find things like this is:
```
grep -r border-radius node_modules/bootstrap/scss/
```
If the default one doesn't fit Joana's design, we should set `$border-radius-lg: CUSTOM;` in our theme `template-ui/src/styles.scss`. I would recommend to continue using REM units as bootstrap default theme does. We should tell Joana. She've been using a 8px grid, and 1rem usually is 16px.

2021-04-08 13:36 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +            <div class="img" :style="backgroundStyle"></div>
Why not use CSS for styling this? In the `<style lang="scss" scoped>` part of the vue file.

2021-04-08 13:36 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +        backgroundImage: `url("${this.thumbnail}")`,
I guess this (backgroundImage) is the only thing to be done in Javascript, the rest can go to the `<style lang="scss" scoped>` part.

2021-04-08 13:36 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +    truncate(text, words = 30) {
There is a `.text-truncate` class in bootstrap. I wonder if you can use that instead. See `node_modules/bootstrap/scss/mixins/_text-truncate.scss`.

2021-04-08 13:36 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +  font-size: normal;
It seems the default is: `$lead-font-size:              $font-size-base * 1.25 !default;` so I would try with: `font-size: $font-size-base;` to use the theme variables.

2021-04-12 10:48 UTC, danigm commented on template-ui/src/components/CarouselCard.vue
> +    truncate(text, words = 30) {
I didn't know about the `text-truncate` class, but I've been testing and this doesn't work because it truncates just one line, it applies the `no-wrap` so the result is not the same.

2021-04-12 12:48 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +    truncate(text, words = 30) {
Ah I see what you are trying to do here now. So where is the truncation at 30 words comes from? Avoiding the carousel to be too tall? Has Joana asked for this? In case this is for keeping the height of the carousel to a reasonable value I would rather truncate by lines. Because by words you will get different results depending on the content. And we have the dependency already for that in our package.json, [vue-clamp](https://justineo.github.io/vue-clamp/demo/). But in any case I would check with Joana how many lines she wants.

There are also pure CSS ways to truncate multiline, but they are tricky so I wouldn't rely on them.

2021-04-12 12:55 UTC, manuq requested changes
Looking great, I commented on the truncation and things we should check with Joana.

2021-04-12 12:55 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +  min-height: 300px;
Where is this value coming from? Is in Joana's blueprints? In any case please move it to a SCSS variable.

2021-04-12 15:45 UTC, danigm commented on template-ui/src/components/CarouselCard.vue
> +    truncate(text, words = 30) {
> Ah I see what you are trying to do here now. So where is the truncation at 30 words comes from? Avoiding the carousel to be too tall?

Yes, that's the main idea. If it grows a lot the image aspect ratio changes too so it can looks weird, depending on the content description length.

2021-04-12 15:52 UTC, danigm commented on template-ui/src/components/CarouselCard.vue
> +  min-height: 300px;
Nope, this is a random value that I set.

2021-04-12 16:00 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +  min-height: 300px;
ok! let's check with Joana then.

2021-04-12 16:16 UTC, danigm commented on template-ui/src/components/CarouselCard.vue
> +    truncate(text, words = 30) {
I didn't know about vue-clamp, that's exactly what we need. I've used that instead of the filter solution.

2021-04-12 16:20 UTC, danigm commented on template-ui/src/components/CarouselCard.vue
> +  min-height: 300px;
I've moved that to a variable in `styles.scss`

2021-04-12 16:28 UTC, manuq approved these changes
Let's merge this, assuming we are going to iterate on the carousel height with Joana.

2021-04-12 16:28 UTC, manuq commented on template-ui/src/components/CarouselCard.vue
> +              <p>by {{ node.author || node.license_owner }}</p>
This made me realize that I forgot to commit CardBody.vue in #46. I just did and there is a "by X" line in there too. We should make it a vuex getter if it's going to be used in CarouselCard too.

2021-04-12 16:28 UTC, merged