template: Polish filter implementation
endlessm/kolibri-channel-custom-web-app pull request #45
Opened 2021-04-08 15:06 UTC by danigm

https://phabricator.endlessm.com/T31717

2021-04-08 18:43 UTC, manuq requested changes
Looks good, just use the theme. I have the docs from bootstrap-vue and bootstrap always around, plus grepping their code.

2021-04-08 18:43 UTC, manuq commented on template-ui/src/components/FilterContent.vue
> +<style lang="scss">
Always set the SCSS as scoped. The only exception is `App.vue`, which has the global styling.

2021-04-08 18:43 UTC, manuq commented on template-ui/src/components/FilterContent.vue
> +  border-radius: 50rem !important;
There is a helper class `.rounded-pill` [from bootstrap](https://getbootstrap.com/docs/4.5/utilities/borders/#border-radius). Grepping their SCSS I found there is a $rounded-pill variable, so you can use it instead. Now, since the button is inside the b-dropdown component, you have to use the `::v-deep` selector so the parent component can affect the children:

```
.b-dropdown {
  ::v-deep .dropdown-toggle {
    border-radius: $rounded-pill;
  }
}
```

2021-04-08 18:43 UTC, manuq commented on template-ui/src/components/FilterContent.vue
> +      class="mr-2 filter-dropdown"
Try no not add custom CSS classes whenever possible. Bootstrap-Vue already adds classes to all components. Since this is the `<b-dropdown>` component you can just use the `.b-dropdown` CSS class.

2021-04-12 11:03 UTC, danigm commented on template-ui/src/components/FilterContent.vue
> +  border-radius: 50rem !important;
Thanks, this does exactly the same. I was trying to apply the border-radius to the dropdown button but I didn't find a good solution, that's the way I just ended removing the `scope` to be able to override the button styles.

2021-04-12 11:59 UTC, manuq approved these changes

2021-04-12 11:59 UTC, merged