template: Add HeaderSearchBar to Header
endlessm/kolibri-channel-custom-web-app pull request #49
Opened 2021-04-13 10:48 UTC by danigm

This patch adds the search input in the Header component and also
applies some style changes to the search input, to add an icon to the
left.

https://phabricator.endlessm.com/T31778

2021-04-13 13:54 UTC, manuq requested changes
Looks great, just more use of the theme variables and bootstrap helper classes are needed.

2021-04-13 13:54 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +  > .input-group-prepend > .input-group-text {
`.input-group-text` is in this component so it doesn't have to be inside the `::v-deep`. Please move it outside since `::v-deep` should be used sparingly.

2021-04-13 13:54 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +    z-index: 4;
No hardcoded values.

```
$ grep index node_modules/bootstrap/scss/_variables.scss 
// Z-index master list
$zindex-dropdown:                   1000 !default;
$zindex-sticky:                     1020 !default;
$zindex-fixed:                      1030 !default;
$zindex-modal-backdrop:             1040 !default;
$zindex-modal:                      1050 !default;
$zindex-popover:                    1060 !default;
$zindex-tooltip:                    1070 !default;
```

2021-04-13 13:54 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +    bottom: 0px;
This is great, I didn't know top 0 and bottom 0 can be used to position vertically.

2021-04-13 17:39 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +    z-index: 4;
Sorry [I was wrong](https://getbootstrap.com/docs/4.0/layout/overview/#z-index).

> To handle overlapping borders within components (e.g., buttons and inputs in input groups), we use low single digit z-index values of 1, 2, and 3 for default, hover, and active states. On hover/focus/active, we bring a particular element to the forefront with a higher z-index value to show their border over the sibling elements.

So I guess 4 is fine.

2021-04-13 17:39 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +    bottom: 0px;
I mean, to *center* vertically.

2021-04-13 17:41 UTC, manuq commented on template-ui/src/components/HeaderSearchBar.vue
> +    left: 0px;
Nit: these don't need the `px` unit, because zero is zero.

2021-04-14 11:06 UTC, danigm commented on template-ui/src/components/HeaderSearchBar.vue
> +    border-radius: $border-radius-lg !important;
oh, yes, that's better

2021-04-14 11:08 UTC, danigm commented on template-ui/src/components/HeaderSearchBar.vue
> +    padding-left: 52px;
I've used the input `padding-x * 2 + 1em`, I've not added the `$icon-size` variable because I don't know exactly how that will affect the template, if every icon in the interface should follow that...

2021-04-14 11:09 UTC, danigm commented on template-ui/src/components/HeaderSearchBar.vue
> +  > .input-group-prepend > .input-group-text {
Good catch, It's inside the template, so I thought that I need to use the deep.

2021-04-14 11:16 UTC, manuq approved these changes
Looks great.

2021-04-14 11:16 UTC, merged