T31871 breadcrumb
endlessm/kolibri-channel-custom-web-app pull request #66
Opened 2021-04-29 19:07 UTC by manuq

https://phabricator.endlessm.com/T31871

2021-05-03 22:54 UTC, dylanmccall requested changes
One small thing, but otherwise I like it. This is definitely way better :)

2021-05-03 22:54 UTC, dylanmccall commented on template-ui/src/components/Breadcrumb.vue
> +    v-if="!isBreadcrumbDisabled"
One nitpick: "isXDisabled" sounds like we're checking some configuration to me, and double negative is :(

Perhaps…

```suggestion
    v-if="hasAncestors"
```

2021-05-04 11:49 UTC, manuq commented on template-ui/src/components/Breadcrumb.vue
> +    v-if="!isBreadcrumbDisabled"
Good point, I'm carrying the old logic here.

2021-05-04 12:07 UTC, manuq commented on template-ui/src/components/Breadcrumb.vue
> +    v-if="!isBreadcrumbDisabled"
I realized that we can just check `v-if="node.ancestors"` directly, without introducing a new method.

2021-05-04 16:44 UTC, dylanmccall approved these changes

2021-05-04 19:42 UTC, merged